### ISSUE TITLE
Error: you don\'t have enough fund","code":21

### ISSUE THREAD

**Issue by montrealblau** [gateio/rest#11]
in nodejs / lib / gate.js fix Buy and Sell endpoints
from:
const BUY_URL = 'api2/1/private/sell';	
const SELL_URL = 'api2/1/private/sell';
to: 
const BUY_URL = 'api2/1/private/buy';	
const SELL_URL = 'api2/1/private/sell';

**Comment by montrealblau** [comment]
placed sell order and it posted buy order instead! 
FIX SELL functionality ASAP!

**Comment by hendra4ditya** [comment]
21
