### ISSUE TITLE
trade history records cannot be retrieved（历史数据API无法读取）

### ISSUE THREAD

**Issue by intheeuro** [gateio/rest#19]
URL: http://data.gate.io/api2/1/tradeHistory/[CURR_A]_[CURR_B]/[TID] does not work and no data can be returned.

URL: http://data.gate.io/api2/1/tradeHistory/[CURR_A]_[CURR_B]/[TID]链接失效无法读取过去1000条数据记录

**Comment by gateio** [comment]
fixed
