### ISSUE TITLE
Problem with error return on order cancel

### ISSUE THREAD

**Issue by FreddyCrugger** [gateio/rest#27]
Hello,

Please try your cancel_order('120969098747', 'lym_usd')  function.

If you do not add an order number you receive an error but if the wrong order number is added(or the order number does not exist), the same response is showing:

```
Array
(
    [result] => 1
    [code] => 0
    [message] => Success
)
```

It should show something like:
```
Array
(
    [result] => 0(or false)
    [code] => 0
    [message] => Error
)
```

**Comment by gateio** [comment]
thx, we have fixed this issue.

**Comment by FreddyCrugger** [comment]
Thank you so much!
