### ISSUE TITLE
How to check if deposit/withdraw are suspended?

### ISSUE THREAD

**Issue by ghost** [gateio/rest#3]
Hello,

I'm wondering how I can check if deposit and withdraw are suspended from the API (using PHP).

The only thing I can think is to request a deposit address but that doesn't seem to work, it still says success. However it doesn't give me the address. Instead it just says success and gives a message to refresh the page, even for currencies that are suspended.

Thanks!

**Comment by ty2u** [comment]
`deposit_address('ada'):

Array
(
    [result] => true
    [addr] => New address is being generated for you, please wait a moment and refresh this page. 
    [message] => Sucess
    [code] => 0
)
`

**Comment by ty2u** [comment]
I'd like to also mention that in the HTML I can see this:

```
        <span class="right-align"><i>0.000000</i><em><a class="err-depo fund-deposit" title="Suspended" for="" maintenance.="" href="javascript:;">Deposit</a><a class="err-depo fund-withdraw" title="Suspended" for="" maintenance.="" href="javascript:;">Withdraw</a></em></span>
```

This part is broken somehow `title="Suspended" for="" maintenance.=""`

**Comment by hendra4ditya** [comment]
35522
