### ISSUE TITLE
amount参数是什么意思？

### ISSUE THREAD

**Issue by Key-CN** [gateio/rest#32]
买入接口中的（amount 最近30天交易量）是什么意思？限制自己最近30天的交易量吗？还是需要自己统计自己最近30天的交易量才可以交易成功？

------------------

下单交易买入API

API URL: https://api.gateio.co/api2/1/private/buy

参数数据提交方式：POST

返回数据格式：JSON

请求参数

参数名 | 参数类型 | 必填 | 描述 | 示例:
-- | -- | -- | -- | --
currencyPair | String | 是 | 交易币种对(如ltc_btc,ltc_btc) | ltc_btc
rate | String | 是 | 价格 | 1000
amount | String | 是 | 最近30天交易量 | 800
orderType | String | 否 | 订单类型(“”：普通订单（默认）；“ioc”：立即执行否则取消订单（Immediate-Or-Cancel，IOC）) | ioc

**Comment by kefengxu** [comment]
买入量
