### ISSUE TITLE
K线的历史记录怎么获取

### ISSUE THREAD

**Issue by ChineseCabbageW** [gateio/rest#34]
https://data.gateio.co/api2/1/candlestick2/[CURR_A]_[CURR_B]?group_sec=[GROUP_SEC]&range_hour=[RANGE_HOUR]

range_hour 这个参数是什么意思？

**Comment by gateio** [comment]
请替换 [CURR_A] 和 [CURR_B] 为您需要查看的币种，GROUP_SEC 和 RANGE_HOUR 替换为需要获取的时间区域.
RANGE_HOUR 为数据时间区间，GROUP_SEC为时间间隔，
例如获取1小时内的分钟线数据：
https://data.gateio.co/api2/1/candlestick2/btc_usdt?group_sec=60&range_hour=1
