### ISSUE TITLE
签名错误

### ISSUE THREAD

**Issue by 728443778** [gateio/rest#35]
我最初通过elixir，发起获取账户balance的请求，服务端返回， invalid key or sign, please re-generate it from your account，然后我用提供的php 例子，修改了下host，返回的还是签名错误，错误都是一样的， invalid key or sign, please re-generate it from your account

**Comment by gateio** [comment]
需要填写本人帐户的API key 和API secret，可以从帐户API Keys设置中获取。

**Comment by kefengxu** [comment]
登陆web系统，在我的账户->安全设置->API keys  输入资金密码和验证码  显示key 和 sign， 并在API文件中填写$key ，$secret 的值

**Comment by 0532** [comment]
> 登陆web系统，在我的账户->安全设置->API keys 输入资金密码和验证码 显示key 和 sign， 并在API文件中填写$key ，$secret 的值

合约时盘api与合约现货api有区别吗 ，如果只查询时时价格 用哪个

**Comment by revilwang** [comment]
合约用的是 APIv4 Keys，如果只是查实时价格这种公开信息，不需要关心用哪个key

**Comment by 0532** [comment]
> 合约用的是 APIv4 Keys，如果只是查实时价格这种公开信息，不需要关心用哪个key

thx  😄
