### ISSUE TITLE
python3.8可以正常使用吗？

### ISSUE THREAD

**Issue by cjrey-good** [gateio/rest#48]
获取marketlist时总是timeout不知道是怎么回事。

**Comment by revilwang** [comment]
Python3可用的，timeout的话有可能跟你的访问地址有关系，你使用的是哪个服务地址?

**Comment by cjrey-good** [comment]
> Python3可用的，timeout的话有可能跟你的访问地址有关系，你使用的是哪个服务地址?

/api2/1/marketlist 这个地址 昨天一直timeout，然后网页直接打开是正常的。今天什么代码都没改就好了。。。不知道什么原因
