### ISSUE TITLE
多次出现错误代码13（系统错误，联系管理员）

### ISSUE THREAD

**Issue by cjrey-good** [gateio/rest#51]
今晚8点左右，多次出现长时间错误代码13的情况，每次将近10分钟，大概3-5次左右。
请问是真的系统服务器错误还是其他原因导致（如访问过频繁等）？
因为实际交易中比较致命，如果是代码问题想避免一下。

**Comment by revilwang** [comment]
你好，能提供一个相对准确的时间吗？有没有当时的一些日志

**Comment by revilwang** [comment]
另外具体的请求是什么？还有对应的请求参数，以及返回的完整错误信息（一般除了code还有message字段）

**Comment by cjrey-good** [comment]
> 另外具体的请求是什么？还有对应的请求参数，以及返回的完整错误信息（一般除了code还有message字段）

谢谢回复。
当时测试没有输出log，有印象的这边跟你说一下。
请求的是：https://data.gateio.life/api2/1/ticker/btc_usdt 
message是Internet xxxx的，xxx的部分忘记了。大意是网络连接错误。
不仅仅是代码上请求出错，直接在浏览器中输入网址请求也返回同样的问题。

**Comment by revilwang** [comment]
现在还有再出现吗？我这边查看是正常的

建议后续提交的issue包含尽可能多的请求相关信息，包括请求时间，请求地址和具体的参数

**Comment by cjrey-good** [comment]
> 现在还有再出现吗？我这边查看是正常的
> 
> 建议后续提交的issue包含尽可能多的请求相关信息，包括请求时间，请求地址和具体的参数

昨天傍晚开始就没出现了，昨天下午持续时间较长，我以为是服务器请求过于频繁导致的IP被限制了。后续如有出现会提供完整log信息。谢谢。
