### ISSUE TITLE
candlestick2中的GROUP_SEC 和RANGE_HOUR 代表意思是？

### ISSUE THREAD

**Issue by cjrey-good** [gateio/rest#52]
如题。
https://data.gateio.life/api2/1/candlestick2/[CURR_A]_[CURR_B]?group_sec=[GROUP_SEC]&range_hour=[RANGE_HOUR]中的后面两个替换参数[GROUP_SEC]\[RANGE_HOUR]分别代表什么意思呢？

如我想获取某个时间点的成交价，这个api是否合适？或者有别的api使用?
(比如我想获取8点的成交价，该如何获取）

**Comment by revilwang** [comment]
GROUP_SEC是指数据点的时间间隔，以秒为单位。RANGE_HOUR表示数据点起始时间距现在有多少小时

比如GROUP_SEC为60，RANGE_HOUR为6，则表示最近6小时按1分钟统计的数据

根据你最近的问题来看，您应该是新使用我们的API，可以考虑试用最新的 APIv4 ，APIv4有完整的交易功能支持，文档地址 https://www.gateio.life/docs/apiv4/zh_CN/index.html#gate-api-v4

**Comment by cjrey-good** [comment]
> GROUP_SEC是指数据点的时间间隔，以秒为单位。RANGE_HOUR表示数据点起始时间距现在有多少小时
> 
> 比如GROUP_SEC为60，RANGE_HOUR为6，则表示最近6小时按1分钟统计的数据
> 
> 根据你最近的问题来看，您应该是新使用我们的API，可以考虑试用最新的 APIv4 ，APIv4有完整的交易功能支持，文档地址 https://www.gateio.life/docs/apiv4/zh_CN/index.html#gate-api-v4

好的 谢谢
