### ISSUE TITLE
API挂单不能成交

### ISSUE THREAD

**Issue by phybrain** [gateio/rest#53]
api请求挂单，盘口显示有挂单价格的单子好几秒 不能成交，你们盘口信息是假的吗

**Comment by revilwang** [comment]
请提供更具体的描述，包括但不限于：

1. 用的是什么 api
2. 盘口信息是怎么获取的

目前的信息我们无法提供有效支持

**Comment by phybrain** [comment]
https://github.com/gateio/gateapi-python
futures/usdt/orders ETH_USDT
我挂单平均几秒钟，ticker api获取的ask和bid，开仓倒是挺顺利，平仓即使盘口有这个价格的他也不能平，我手动看app盘口下单也是这样，请显示真实的深度

**Comment by revilwang** [comment]
如果需要更及时的价格，推荐订阅 WebSocket，API 获取的数据本身是有延迟的
