### ISSUE TITLE
withdraw_fix_on_chains returns None since today

### ISSUE THREAD

**Issue by Programmierus** [gateio/rest#61]
Based on my issue [here](https://github.com/gateio/gateapi-python/issues/58) a very useful data was added to `list_withdraw_status()` method. But since today it returns `None`, i.e. got broken:

Example return (see `withdraw_fix_on_chains` - should be **not None**, but return real data)

```
{
 'currency': 'USDT',
 'deposit': '0',
 'name': 'Tether',
 'name_cn': 'Tether',
 'withdraw_amount_mini': '50',
 'withdraw_day_limit': '300000',
 'withdraw_day_limit_remain': '284999.706',
 'withdraw_eachtime_limit': '284999.706',
 'withdraw_fix': '40',
 'withdraw_fix_on_chains': None,
 'withdraw_percent': '0%'
}
```

**Comment by revilwang** [comment]
It's been fixed from the server side.
