### ISSUE TITLE
websocket service

### ISSUE THREAD

**Issue by herbomiy** [gateio/rest#7]
Do you support websocket？

**Comment by andreMc05** [comment]
Yes. What are the requirements?

**Comment by KarryLi2** [comment]
can you give websocket api？

**Comment by KarryLi2** [comment]
can you give me websocket api？

**Comment by KarryLi2** [comment]
Can you give me websocket api？

**Comment by datoufeixia** [comment]
Sorry, we do not support websocket api yet

**Comment by gateio** [comment]
WebSocket API Document https://gate.io/docs/websocket/index.html
